CC = c++
CFLAGS = -Wall -Wextra -Werror -std=c++98

SRCS = main.cpp\
	Zombie.cpp\
	zombieHorde.cpp\

OBJS = $(SRCS:.cpp=.o)
NAME = Moar_brainz!

all: $(NAME)

$(NAME): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^

%.o: %.cpp
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re